export const GUIA_CONSTANTS = {
  SERVICIOS: {
    RECAUDO_CONTRA_ENTREGA: 1
  },
  VALIDACIONES: {
    MAX_REFERENCIA_LENGTH: 50,
    MIN_VALOR_RECAUDAR: 1,
    MAX_VALOR_RECAUDAR: 16000000
  }
} as const; 